run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocyclo
    - dupl
    - goconst
    - gocritic
    - godox
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  gomnd:
    checks: argument,case,condition,operation,return,assign
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - commentFormatting
      - hugeParam
      - ifElseChain
      - octalLiteral
      - whyNoLint
  gosec:
    excludes:
      - G101 # Look for hardcoded credentials
      - G102 # Bind to all interfaces
      - G104 # Audit errors not checked
      - G107 # Url provided to HTTP request as taint input
      - G201 # SQL string formatting
      - G202 # SQL string concatenation
      - G204 # Audit use of command execution
      - G301 # Poor file permissions used when creating a directory
      - G302 # Poor file permissions used with chmod
      - G303 # Poor file permissions used when creating a file
      - G304 # File path provided as taint input
      - G305 # File path traversal when extracting zip archive
      - G306 # Poor file permissions used when writing to a file
      - G307 # Poor file permissions used when creating a file
      - G401 # Detect the usage of DES, RC4, MD5 or SHA1
      - G402 # Look for bad TLS connection settings
      - G403 # Ensure minimum RSA key length of 2048 bits
      - G404 # Use of weak random number generator (math/rand instead of crypto/rand)
      - G501 # Import blacklist: crypto/md5
      - G502 # Import blacklist: crypto/des
      - G503 # Import blacklist: crypto/rc4
      - G504 # Import blacklist: net/http/cgi
      - G505 # Import blacklist: crypto/sha1
      - G601 # Implicit memory aliasing in for loop

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - gocyclo
        - dupl
        - gosec
    - path: vendor/
      linters:
        - all
    - path: cmd/
      linters:
        - gosec
        - gocyclo
        - dupl
        - goconst
        - gomnd
    - path: internal/
      linters:
        - gosec
        - gocyclo
        - dupl
        - goconst
        - gomnd
    - path: pkg/
      linters:
        - gosec
        - gocyclo
        - dupl
        - goconst
        - gomnd

severity:
  default-severity: error
