version: "3.9"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: business_exchange
      MYSQL_USER: app
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 15s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 15s
      retries: 10

  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      APP_ENV: development
      APP_PORT: 8080
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: app
      DB_PASSWORD: app_password
      DB_NAME: business_exchange
      REDIS_ADDR: redis:6379
      REDIS_DB: 0
      REDIS_PASSWORD: ""
      JWT_SECRET: changeme-super-secret
      JWT_ISSUER: trade_company
      JWT_EXPIRE_MINUTES: 60
    ports:
      - "8080:8080"

  adminer:
    image: adminer:4
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  db_data: 