version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_CHARSET=${DB_CHARSET}
      - DB_PARSE_TIME=${DB_PARSE_TIME}
      - DB_LOC=${DB_LOC}
      - DB_MAX_IDLE_CONNS=${DB_MAX_IDLE_CONNS}
      - DB_MAX_OPEN_CONNS=${DB_MAX_OPEN_CONNS}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_POOL_SIZE=${REDIS_POOL_SIZE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_EXPIRE_MINUTES=${JWT_EXPIRE_MINUTES}
      - JWT_REFRESH_EXPIRE_DAYS=${JWT_REFRESH_EXPIRE_DAYS}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CORS_ALLOWED_METHODS=${CORS_ALLOWED_METHODS}
      - CORS_ALLOWED_HEADERS=${CORS_ALLOWED_HEADERS}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - UPLOAD_DIR=${UPLOAD_DIR}
      - ALLOWED_IMAGE_TYPES=${ALLOWED_IMAGE_TYPES}
      - DEFAULT_PAGE_SIZE=${DEFAULT_PAGE_SIZE}
      - MAX_PAGE_SIZE=${MAX_PAGE_SIZE}
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
    depends_on:
      - cloud-sql-proxy
    networks:
      - app-network

  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.1
    command: >
      --instances=${CLOUD_SQL_INSTANCE_CONNECTION_NAME}=tcp:3306
      --credentials-file=/secrets/cloud-sql-credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/secrets/cloud-sql-credentials.json:ro
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
