CREATE TABLE listings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    price BIGINT NOT NULL,
    category VARCHAR(100),
    `condition` VARCHAR(50),
    location VARCHAR(255),
    status ENUM('active', 'sold', 'deleted') DEFAULT 'active',
    owner_id BIGINT NOT NULL,
    view_count INT DEFAULT 0,
    brand_story TEXT,
    rent BIGINT DEFAULT 0,
    floor INT DEFAULT 0,
    equipment TEXT,
    decoration VARCHAR(100),
    annual_revenue BIGINT DEFAULT 0,
    gross_profit_rate DECIMAL(5,2) DEFAULT 0.00,
    fastest_moving_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    phone_number VARCHAR(50),
    square_meters DECIMAL(10,2) DEFAULT 0.00,
    industry VARCHAR(100),
    deposit BIGINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);
