name: staging
url: https://business-exchange-staging-xxxxx-uc.a.run.app
protection_rules:
  - required_reviews: 1
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    required_status_checks: []
    restrictions: {}
