// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
}

type CreateListingInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Price       int     `json:"price"`
	Location    *string `json:"location,omitempty"`
}

type Listing struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Price       int     `json:"price"`
	Location    *string `json:"location,omitempty"`
	OwnerID     string  `json:"ownerID"`
	CreatedAt   *string `json:"createdAt,omitempty"`
	UpdatedAt   *string `json:"updatedAt,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}
